name: privacy_shield
description: A comprehensive Flutter plugin to protect your app's content from being exposed in the App Switcher (recent apps view) and to prevent screenshots/screen recording.
version: 0.1.0
homepage: https://github.com/thanseer02/privacy_shield
repository: https://github.com/thanseer02/privacy_shield
issue_tracker: https://github.com/thanseer02/privacy_shield/issues
environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.privacy_shield
        pluginClass: PrivacyShieldPlugin
      ios:
        pluginClass: PrivacyShieldPlugin

